### ISSUE TITLE
Artyści- Karol Okoński- link do wystawy zwraca 404 + brak artysty w wersji en.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/festiwal-swiatla#124]
Artyści - Karol Okoński - link, który powinien przekierować do opisu wystawy "Lampa Camelia" zwraca 404.

Brak opisu tego artysty w wersji en (powinien znajdować się pomiędzy Kariną Wierzbowską, a Kingą Marszałkowską).

<img width="1280" alt="Karol" src="https://github.com/hs3city/festiwal-swiatla/assets/92811043/f1106bba-ab3c-48c6-9653-d2c699840ff1">

<img width="1280" alt="brak Karola" src="https://github.com/hs3city/festiwal-swiatla/assets/92811043/ae89e9b6-6c37-4f6b-8205-b649ea1b50b7">

**Comment by DoomHammer** [comment]
W tym roku nie występuje, usunąłem już.
