### ISSUE TITLE
Artyści - Daria Berg -literówki w bio.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/festiwal-swiatla#20]
Opis:
Artyści - w bio Darii Berg są literówki. Do poprawienia na "pojedyncza" i "duży".
![Literówki](https://user-images.githubusercontent.com/92811043/167002097-e55d20e8-e31a-4e91-9930-4826f23439aa.PNG)

Przeglądarka: Google Chrome Wersja 92.0.4515.131
Windows 8.1 6.3.9600.17415

**Comment by KGrzeg** [comment]
Rozwiązane w #34 oraz #24
