### ISSUE TITLE
Artyście- Daria Berg- w opisie wystawy zdanie do zmiany.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/festiwal-swiatla#21]
Opis:
Zakładka Artyści - Daria Berg. Proponuję skrócić i zmienić nieco zakreślone zdanie na:
Wykonując fotografie Daria Berg miała na celu stworzenie obrazu, który zawiśnie na ścianach, jednocześnie będąc uniwersalnym i jedynym w swoim rodzaju oraz wnoszącym do przestrzeni pozytywną energię.
![Zdanie](https://user-images.githubusercontent.com/92811043/167004644-cddd7e98-0c28-401e-844c-79083c2758ba.PNG)

Przeglądarka: Google Chrome Wersja 92.0.4515.131
Windows 8.1 6.3.9600.17415

**Comment by KGrzeg** [comment]
Akapit został przepisany w  #24, więc chyba można zamknąć?

**Comment by AgnieszkaS4** [comment]
@KGrzeg ostatnie zdanie jest powtórzeniem wcześniejszego zdania. Fragmenty powtarzają się praktycznie 1:1 (zaznaczone). Proponuję wyrzucić ostatnie zdanie. Wcześniejsze zawiera już cały potrzebny opis.
![Daria Berg ostatnie zdanie](https://user-images.githubusercontent.com/92811043/167290307-f0bdfbf0-e01d-4ff1-b187-591bc8bbe3ea.PNG)

.

**Comment by KGrzeg** [comment]
@ema-html Co o tym sądzisz?
