### ISSUE TITLE
Organizatorzy - w opisie "O nas" brak przekierowania do FB CUMY warsztat otwarty.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/festiwal-swiatla#22]
Opis:
Zakładka Organizatorzy - w opisie "O nas" brak linka przekierowującego do Facebooka CUMY warsztat otwarty.

![Brak przekierowania](https://user-images.githubusercontent.com/92811043/167006282-99610d95-e608-4e16-9431-79b056cd7979.PNG)

Przeglądarka: Google Chrome Wersja 92.0.4515.131
Windows 8.1 6.3.9600.17415

**Comment by KGrzeg** [comment]
Ta strona? https://www.facebook.com/cumy.stocznia/
CUMY nie ma witryny internetowej?

**Comment by AgnieszkaS4** [comment]
Tak, chodzi o ten link do FB. 
CUMY nie ma strony, ale @tgbdc7 potwierdź proszę nam jeszcze.

**Comment by tgbdc7** [comment]
tak można dać link do fb  https://www.facebook.com/cumy.stocznia/ @KGrzeg

**Comment by AgnieszkaS4** [comment]
@KGrzeg sprawdzone. Działa.
