### ISSUE TITLE
Sprawdzone i działające prawidłowo sekcje.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/festiwal-swiatla#28]
Gra miejska- link do regulaminu działa ok. W wersji mobilnej też.

Nowa mapa atrakcji (różowa) - bardziej czytelna. W wersji mobilnej zoom działa i mapa nadal pozostaje bardzo czytelna.

Wersja mobilna:
- program FŚ czytelny, zoom działa
- zakładka projekty - przekierowanie do szczegółowego programu FŚ działa
- mapa interaktywna w wersji mobilnej:
 1. przekierowanie do Google Maps działa 
 2. Zoom działa
 3. udostępnianie na FB, Twitterze, e-mail działa. 
 [ ] Nie działa opcja udostępniania SMS-em @KGrzeg 
 4. legenda mapy działa, tylko, że po jej rozwinięciu zasłania praktycznie całość mapy. 
[ ] Pytanie, czy można zmniejszyć legendę, tak aby nie zasłaniała mapy?
5. checkboxy pokazów, gry miejskiej, warsztatów, wystaw i parkingu działają. 
W wersji na lapku:
- program czytelny
- zakładka projekty - przekierowanie do szczegółowego programu FŚ działa
- mapa interaktywna:
1. przekierowanie do Google Maps działa 
 2. Zoom działa
 3. udostępnianie na FB, Twitterze, e-mail działa. 
 [ ] opcja umieść na mojej stronie - przekierowuje do Google Maps, pytanie, czy tak ma być?
5. legenda mapy działa
6. checkboxy pokazów, gry miejskiej, warsztatów, wystaw i parkingu działają.
7. lista wszystkich elementów w legendzie - po wybraniu danej atrakcji z listy bardzo czytelnie jest ona zaznaczona na mapie. 

Organizatorzy, partnerzy, patronat, patronat medialny - przekierowania do stron działają.
- Pytanie, czy Monochromancer nie powinien mieć przekierowanie do swojego insta? Ich logo przekierowuje na stronę główną FŚ. @KGrzeg 
- Ankagra pisała, aby usunąć z partnerów logo enauczanie.

Warsztaty - Zapisy - sekcje na stronie działające prawidłowo:
- zapis na warsztaty z poziomu strony FŚ
- przycisk „cofnij”, „rezerwuj”, „dalej"
- licznik czasu rezerwacji biletów
- przekierowania do regulaminu serwisu Evenea i polityki prywatności 
- walidacja pól formularza do rejestracji biletów.

**Comment by KGrzeg** [comment]
Poproszę o link do Monochromancera. Nie wiedziałem dokąd ma prowadzić, a Google nie udzieliło mi jednoznacznej odpowiedzi :(
@Dreat

**Comment by KGrzeg** [comment]
Dopisuję też do listy zmian:
- Wśród partnerów przesunąć patronat powyżej partnerów
- Poprawić logo HS3, aby wyświetlało się dobrze na urządzeniach bez zainstalowanej odpowiedniej czcionki

**Comment by KGrzeg** [comment]
I to 
![image](https://user-images.githubusercontent.com/27036554/167400491-1169584b-b679-46f7-8109-0ca188769dcf.png)

**Comment by KGrzeg** [comment]
I to 
![image](https://user-images.githubusercontent.com/27036554/167411608-7f53bc5a-0caf-460e-9bad-cda872305145.png)

(Przepraszam za zawłaszczenie sobie issue jako _listę to do_, ale i tak zmiany wejdą na raz, to będzie mniej klikania później :P )

**Comment by AgnieszkaS4** [comment]
> 
@KGrzeg  https://www.instagram.com/monochromancer/

**Comment by AgnieszkaS4** [comment]
Logo Code:Me też jest ucięte
![Logo CM](https://user-images.githubusercontent.com/92811043/167477322-f8c3f0e9-5167-4e6f-9e53-f066c4089d89.PNG)
.
W wersji mobilnej jest ok.
@KGrzeg właśnie o to chodziło, żeby w tym issue była checklista + to do :)

**Comment by KGrzeg** [comment]
@AgnieszkaS4 
> udostępnianie na FB, Twitterze, e-mail działa.
[ ] Nie działa opcja udostępniania SMS-em @KGrzeg

Niewiele możemy z tym zrobić, ponieważ mapa w całości obsługiwana jest przez Google, a my tylko wyświetlamy ją u siebie bez większej integracji. 

> legenda mapy działa, tylko, że po jej rozwinięciu zasłania praktycznie całość mapy.
[ ] Pytanie, czy można zmniejszyć legendę, tak aby nie zasłaniała mapy?

Tu podobnie jak wyżej, jednak myślę że tak jest dobrze, inaczej legenda nie będzie czytelna. Sposób postępowania powinien wyglądać tak, że użytkownik zagląda do legendy, a następnie ją ukrywa aby przyjrzeć się mapie.

Brakuje nam linku do witryny L'arT, jeśli takowa w ogóle istnieje. Linku brakuje przy logo oraz gdzieś w treści strony (#47)

Przy okazji - [Github pozwala drukować checkboxy](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists):

| Kod | Efekt |
| ------------- | ------------- |
| `[ ] podpunkt`  | [ ] podpunkt  |
| `- [ ] podpunkt` | <ul><li>- [ ] podpunkt</li></ul>  |

**Comment by DoomHammer** [comment]
Na ile to jest aktualne, @AgnieszkaS4 ?

**Comment by AgnieszkaS4** [comment]
@DoomHammer to checklista z poprzedniego roku :) Aktualne rzeczy są na Trello w karcie "testowanie strony festiwalu".

**Comment by DoomHammer** [comment]
Gdzie na Trello?
