### ISSUE TITLE
Evenea - nieprawidłowe połączenie dnia tygodnia z datą warsztatów Camera Obscura.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/festiwal-swiatla#29]
Opis:
Evenea - w zapisie na warsztaty, pozycja nr. 4 Camera Obscura podany nieprawidłowy dzień tygodnia w połączeniu z datą warsztatu. Prawidłowo powinna być sobota zamiast piątku. 14 maja to sobota. 
![Evenea błąd w dniu tygodnia powinna być sobota](https://user-images.githubusercontent.com/92811043/167252645-d1dd1d79-85d9-4317-a7b6-c63783077823.PNG)

Info z datami warsztatów z google drive:

![Camera Obscura info z drive daty i godziny](https://user-images.githubusercontent.com/92811043/167252747-29f78a36-8b09-42da-8f43-86999017a950.PNG)

Przeglądarka: Google Chrome Wersja 92.0.4515.131
Windows 8.1 6.3.9600.17415

**Comment by tgbdc7** [comment]
poprawione @AgnieszkaS4  sprawdź proszę

**Comment by AgnieszkaS4** [comment]
Sprawdziłam z ostatnim deployem, wyszukując stronę festiwalu przez Google, ze stroną podpiętą na FB i w wersji mobilnej. We wszystkich czterech przypadkach nadal przy zapisach na ten warsztat na Evenei jest piątek 14 maja zamiast prawidłowej wersji, czyli sobota 14 maja godz. 13:00.
Poprawisz @tgbdc7 ?

**Comment by tgbdc7** [comment]
a teraz? @AgnieszkaS4

**Comment by AgnieszkaS4** [comment]
@tgbdc7 jest ok. Zamykam.
