### ISSUE TITLE
Strona FŚ - zdublowane zapisy na warsztaty Camera Obscura piątek godz. 13:00.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/festiwal-swiatla#30]
Opis:
Na stronie FŚ zdublowane zapisy na warsztaty Camera Obscura na piątek godz. 13:00. 
Prawidłowo w poz. nr. 4 przy tych warsztatach powinna być sobota godz. 13:00.
![Camera Obscura 3 x piątek](https://user-images.githubusercontent.com/92811043/167253434-3cf86454-2c4a-43b2-a42e-93492a014c8e.PNG)

Info z datami warsztatów z google drive:
![Camera Obscura info z drive daty i godziny](https://user-images.githubusercontent.com/92811043/167253395-48f62704-279d-49c1-ab0a-2f4dacb70c3b.PNG)

Przeglądarka: Google Chrome Wersja 92.0.4515.131
Windows 8.1 6.3.9600.17415

**Comment by tgbdc7** [comment]
poprawione, @AgnieszkaS4 prosze o sprawdzenie

**Comment by AgnieszkaS4** [comment]
Sprawdziłam z ostatnim deployem, wyszukując stronę festiwalu przez Google, ze stroną podpiętą na FB i w wersji mobilnej. We wszystkich czterech przypadkach nadal na stronie FŚ są 3 x warsztaty Camera Obscura w piątek o godz. 13:00. 
Pozycja nr. 4 tych warsztatów powinna być w sobotę o godz. 13:00.
@tgbdc7 poprawisz?

**Comment by AgnieszkaS4** [comment]
Teraz jest ok @tgbdc7.
