### ISSUE TITLE
Strona FŚ - podany błędny dzień tygodnia w zapisie na pokaz w Mobilnym Planetarium.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/festiwal-swiatla#31]
Opis:
Na stronie FŚ w zapisach na pokazy w Mobilnym Planetarium dwa razy podany błędny dzień tygodnia. Poz. nr. 4 i 6 zamiast piątku godz. 12:00 i 16:00, powinna być sobota godz. 12:00 i 16:00.
![Planetarium zmienić na sobotę](https://user-images.githubusercontent.com/92811043/167254447-ed94e4d7-d16b-4a2d-8472-a9a218c08228.PNG)
Info z datami pokazów z google drive:
![Planetarium info z drive](https://user-images.githubusercontent.com/92811043/167254473-4f2cbd68-4611-49af-9d26-7dc2209ef32e.PNG)

Przeglądarka: Google Chrome Wersja 92.0.4515.131
Windows 8.1 6.3.9600.17415

**Comment by tgbdc7** [comment]
Poprawione - Po ustaleniach z Magdą dodaliśmy jeszcze jeden termin na Mobilne planetarium w piątek godzina 16:00

**Comment by AgnieszkaS4** [comment]
@tgbdc7 sprawdzone. Wszystko się zgadza.
