### ISSUE TITLE
Evenea zapisy - nieprawidłowe połączenie dnia tygodnia z datą pokazu w Mobilnym Planetarium.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/festiwal-swiatla#32]
Opis:
Evenea - w zapisach na pokazy w Mobilnym Planetarium nieprawidłowo połączony dzień tygodnia z datą. 
Zamiast piątek 15 maja, powinien być piątek 13 maja godz. 11:00.
![Evenea planetarium powinno być 13 maja](https://user-images.githubusercontent.com/92811043/167254938-378d27fa-ec4b-49ca-a54c-45a36b5c4070.PNG)
Info z datami pokazów z google drive:

![Planetarium drive piątek](https://user-images.githubusercontent.com/92811043/167255118-7c43e4c5-98db-461e-9df6-40cb6ba1cd88.PNG)

Przeglądarka: Google Chrome Wersja 92.0.4515.131
Windows 8.1 6.3.9600.17415

**Comment by tgbdc7** [comment]
poprawione. Dzięki 

to też jest wina evenei bo ta data to jest do kiedy są dostępne bilety. Celowo ustawiłem, żeby była taka sama data.

**Comment by AgnieszkaS4** [comment]
Sprawdzone @tgbdc7. Teraz jest ok.
