### ISSUE TITLE
Evenea zapisy - zdublowany i nieprawidłowo połączony dzień tygodnia z datą pokazu w Mobilnym Planetarium.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/festiwal-swiatla#33]
Opis:
Evenea zapisy - nieprawidłowe połączenie dnia tygodnia i dat pokazów w Mobilnym Planetarium: piątek 14 maja godz. 12:00 i 16:00.
Powinna być sobota 14 maja godz. 12:00, kolejny pokaz również w sobotę 14 maja o godz. 16:00.
![Evenea planetarium zmienić na sobotę](https://user-images.githubusercontent.com/92811043/167255752-5dc2fa2b-27fd-437b-b6d0-f646a91ab3d0.PNG)

Info z opisu pokazu z datami i godzinami:
![Planetarium sobota](https://user-images.githubusercontent.com/92811043/167256007-25361032-72fa-497d-a14b-d2b9d79bbf76.PNG)

Przeglądarka: Google Chrome Wersja 92.0.4515.131

**Comment by tgbdc7** [comment]
to ten sam błąd. @AgnieszkaS4 sprawdź proszę teraz sekcje Mobilne planetarium.

**Comment by AgnieszkaS4** [comment]
Sprawdzone. Piątek godz. 16:00 też jest dodane, tak jak pisałeś. Wszystko się zgadza. 
Zamykam.
