### ISSUE TITLE
Evenea: Brak aktywnego linka przekierowującego do Instagrama FŚ.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/festiwal-swiatla#35]
Evenea: W danych kontaktowych brak aktywnego linka przekierowującego do Instagrama FŚ.
W wersji mobilnej ta sama sytuacja.

![Evenea insta](https://user-images.githubusercontent.com/92811043/167473543-f1a85e16-417a-4833-a5d7-3c6c7bd47a01.PNG)

Google Chrome Wersja 92.0.4515.131

Wersja mobilna: 
Google Chrome Wersja 92.0.4515.131
Android 11; RKQ1. 210503.001

**Comment by tgbdc7** [comment]
Poprawione
