### ISSUE TITLE
Organise repository

### ISSUE THREAD

**Issue by KGrzeg** [hs3city/festiwal-swiatla#5]
Maybe it's time to organise repo structure?
There're more than 1 project in wiki, so we should make individual directory for each and additional one for webpage.

https://festiwalswiatla.hs3.pl/Waga_z_ledem.ino :P

**Comment by DoomHammer** [comment]
Yup, a separate repo for Cyberhopscotch would help here.

**Comment by DoomHammer** [comment]
New one goes here: https://github.com/hs3city/cyberskakanka
