### ISSUE TITLE
Docs/ formularz do współtworzenia FŚ - błędne daty festiwalu i logo z poprzedniej edycji.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/festiwal-swiatla#57]
Docs/ formularz na stronie głównej, podlinkowany w "dołącz do nas" zawiera błędne daty festiwalu - w logo i w opisie, powinien być 13 i 14.05. Logo FŚ jest z poprzedniej edycji.
<img width="1280" alt="main page" src="https://user-images.githubusercontent.com/92811043/231535974-48064cd7-4cbe-48ec-a32a-6bcca7e89127.png">

<img width="1280" alt="ankieta" src="https://user-images.githubusercontent.com/92811043/231535934-b0203917-e47c-46fa-94f0-1dec436ed1ca.png">

**Comment by kinga-marszalkowska** [comment]
Done
