### ISSUE TITLE
Artyści - Bio- wyraz bio ma różne odcienie - brak spójności w kolorystyce.

### ISSUE THREAD

**Issue by AgnieszkaS4** [hs3city/festiwal-swiatla#79]
Artyści - wyraz bio, znajdujący się pod avatarem ze zdjęciem u każdego artysty ma inny odcień - brak zachowanej spójności w kolorystyce tego elementu (biały i szary).

<img width="1280" alt="bio white color sample" src="https://github.com/hs3city/festiwal-swiatla/assets/92811043/be485a0d-c78e-439a-8e1f-2ad285fe5961">

<img width="1280" alt="bio grey color sample" src="https://github.com/hs3city/festiwal-swiatla/assets/92811043/532ddcdd-3f4a-4984-8373-bbc653b60284">

**Comment by DoomHammer** [comment]
Powinno być już lepiej, możesz sprawdzić?

**Comment by AgnieszkaS4** [comment]
Tak, wszędzie jest spójny kolor.
